### ISSUE TITLE
Can't output graphics as wrapped React elements.

### ISSUE THREAD

**Issue by jmak** [mikaelvesavuori/figmagic#102]
**Describe the bug**
Reading documentation I have an impression that outputting graphics (elements that are placed on Graphics page in Figma file) as wrapped react elements is build into the Figmagic library. I manage only to export everything as svgs. I tried to use custom template but with no success.

**My config**

`"figmagic": "^4.0.15"`

```
{
  "fontUnit": "rem",
  "remSize": "10",
  "outputFileName": "figma.json",
  "outputFolderBaseFile": ".figmagic",
  "outputFolderTokens": "tokens",
  "outputFolderElements": "elements",
  "outputFormatGraphics": "svg",
  "outputFolderGraphics": "./src/icons",
  "outputGraphicElements": true,
  "outputGraphicElementsMap": true,
  "syncGraphics": true,
  "outputFormatCss": "mjs",
  "outputFormatTokens": "mjs",
  "spacingUnit": "rem",
  "usePostscriptFontNames": true,
  "templates": {
    "templatePathGraphic": "./node_modules/figmagic/templates/graphic",
    "templatePathReact": "./node_modules/figmagic/templates/react",
    "templatePathStyled": "./node_modules/figmagic/templates/styled",
    "templatePathStorybook": "./node_modules/figmagic/templates/story"
  }
}
```

When I run: `"figmagic:graphics": "node ./node_modules/figmagic/build/index.js --syncGraphics"` I get only svg files.

When I run `"figmagic:sync": "node ./node_modules/figmagic/build/index.js --syncElements --syncGraphics"` I get one element that I have in Elements page but I don't get wrapped React elements for svg files

**Expected behavior**
SVG icons placed on Graphics page in Figma are exported as React components

**Desktop (please complete the following information):**
 - macOS

**Comment by mikaelvesavuori** [comment]
Hi!

Given that you set `"syncElements": true` in the config (or use `--syncElements`) you should be getting a result similar to the attached image.

![figmagic-wrapped-svg](https://user-images.githubusercontent.com/23580994/114553630-210c8d00-9c66-11eb-99c4-e08b4e1f5780.png)

**Comment by mikaelvesavuori** [comment]
Hi @jmak,

I will be closing this since this should be able to be corrected as per above. I will look into updating docs to clarify!

**Comment by jmak** [comment]
Thanks for your explanation.
