### ISSUE TITLE
Figma Low Code support

### ISSUE THREAD

**Issue by KlausSchaefers** [mikaelvesavuori/figmagic#105]
**Is your feature request related to a problem? Please describe.**
Hi, I am working on a similar project for Vue. I have also created a plugin for Figma to add some meta data, e.g. if an element is a text input etc. You can find more information here:

https://www.figma.com/community/plugin/858477504263032980/Figma-Low-Code

Would you be interested in collaborating? For instance by sharing the plugin and using the same meta information?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mikaelvesavuori** [comment]
Hi @KlausSchaefers! Sorry for the inordinate delay in answering. This is very interesting. Send me an email at [MYNAME] at gmail dot com and let's that there?
