### ISSUE TITLE
Writing Figma graphics as elements errors out if their name has special characters

### ISSUE THREAD

**Issue by vilanz** [mikaelvesavuori/figmagic#112]
**Describe the bug**
If a graphic is named like `action / reorder` (instead of just `ActionReorder`), [the code for writing graphics ignores the special characters like /](https://github.com/mikaelvesavuori/figmagic/blob/4c1625a7c828f13446c96680296c3c2557b6484c/bin/frameworks/string/camelize.ts#L6).

But the code for writing elements [doesn't ignore them](https://github.com/mikaelvesavuori/figmagic/blob/0b568667046a4e2c85c91ed16996721429ba0ff2/bin/frameworks/string/toPascalCase.ts#L6).
It tries to read from `{outputFolderGraphics}/Action/Reorder.svg` and finds nothing - which later on will throw a `No data passed to cleanSvgData()` afterwards.

I know I can ask the designer to fix the names, but we've got 234 icons... Currently we're manually creating the React components from SVGs anyway, introducing elements would be a plus.

**To Reproduce**
1. Have a Figma graphic named `file / upload`
2. Make Figmagic process it as a element
```json
  "syncGraphics": true,
  "outputFolderGraphics": "src/Icons/svgs",
  "outputGraphicElements": true,
  "syncElements": true,
  "outputFolderElements": "src/Icons/elements",
  "outputFormatElements": "tsx",
```
3. An `No data passed to cleanSvgData()` error will occur

**Expected behavior**
Special characters are ignored when writing elements and everything goes well.

**Extra info:**
 - OS: Windows 10

**Comment by mikaelvesavuori** [comment]
Hi! Thanks for opening this.

I will need to investigate (and potentially clean this). The behavior is known and it may be non-trivial to support because of slashes being formed as a file path (meaning they end up as nested folders instead of as actual characters). Potentially an easy fix, potentially not.

**Comment by mikaelvesavuori** [comment]
I am trying to push out `4.3.5` now that should fix this.

There was previously no support whatsoever for nested names on graphics or components. This is added in the mentioned release.

Please note that "special characters" do not get any specific handling at all (thus implicitly they are supported). The exception was of course the forward slash (`/`) which is now supported.
