### ISSUE TITLE
Fixing shadows (box-shadow)

### ISSUE THREAD

**Issue by joeleduardo** [mikaelvesavuori/figmagic#13]
Hi im started to used your figmagic and is awesome!!! but looking into shadows tokens result file i saw that are take a extra `param` in the shadow and display it a wrong effect... so my question is what is reason with not update this line..

` shadowObject[name] = ${X}px ${Y}px 10px ${RADIUS}px rgba(${R}, ${G}, ${B}, ${A});`

To 

` shadowObject[name] = ${X}px ${Y}px ${RADIUS}px rgba(${R}, ${G}, ${B}, ${A});`

Inside this file https://github.com/mikaelvesavuori/figmagic/blob/master/bin/functions/setupShadowTokens.mjs

Line: 42

**Comment by mikaelvesavuori** [comment]
Fixed in 2.1.8
