### ISSUE TITLE
Unit configuration option for borderWidths, radii and shadows

### ISSUE THREAD

**Issue by alehar9320** [mikaelvesavuori/figmagic#145]
**Problem statement**
I'm attempting to change the _unit_ of all figmagictokens from _px_ to _rem_ and get frustrated by the _lack of configuration options._

**Describe the solution you'd like**
I'd like the possibility of changing each figmagic token category individually. Currently, Figmagic lacks the options for _borderWidths_, _radii_ and _shadows_.

**Describe alternatives you've considered**
Manually converting them, post Figmagic has run, using the same base unit as set in Figmagic's configuration file (figmagic.json).

**Additional context**
Whether the web dev community consensus is to move towards the adoption of _rem_ for the above-mentioned categories should be besides the point, if the unit configuration option exists for some categories, it should be there for all.

I do however still welcome discussions on the pros and cons of using rems for each and every category. At the heart of it, rems do make sense whenever the content seeks to be responsive. Perhaps it should be the future default of Figmagic (even though Figma doesn't support anything other than px yet).

**Comment by mikaelvesavuori** [comment]
I got less time than needed, but now it's just really the radii that's left needing a fix (that solution uses `normalizeUnits()` which requires a somewhat different approach on my end).

**Comment by mikaelvesavuori** [comment]
This is now done, and I'll be releasing it in `4.3.6` shortly.
