### ISSUE TITLE
Figma erroneously sets certain font weights to 400

### ISSUE THREAD

**Issue by Julian-Rojo-Beezy** [mikaelvesavuori/figmagic#151]
**Describe the bug**
Font weight values are exported as "400" when there is a whitespace in their names in the Figma font-weight selector (e.g. in the "Inter" font).

**To Reproduce**
1. Use any design-token enabled file, such as a duplicate of https://www.figma.com/community/file/821094451476848226.
2. Change the font-weights and font-families to "Inter" font family (or any other family with whitespace in their font-weight options: "Extra Light", "Semi Bold", but not "ExtraLight" nor "SemiBold").
3. Apply some of those weights, and optionally other without whitespace for comparison.
4. Check in the "Inspect" Figma right panel, under the Typography section, how the weights are different according to the selected options.
5. Run Figmagic and check the values of the `fontWeights` tokens. Those that have a whitespace in Figma are exported as 400 in all the cases.

**Expected behavior**
The value of those tokens should be the same as the ones shown in the Typography section.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/70134058/141319022-73a107a2-8cf2-4ba4-82cd-a59737f588c3.png)
![imagen](https://user-images.githubusercontent.com/70134058/141319518-bc0b0352-5caa-4d37-86ef-1c28dee5de2b.png)
![imagen](https://user-images.githubusercontent.com/70134058/141319771-86a308b1-8473-4866-8315-44043c0e67cc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: figmagic 4.4.0

**Additional context**
`usePostscriptFontNames` has no effect on the wrong weight values.

**Comment by mikaelvesavuori** [comment]
Hey!

Interesting. The code in Figmagic for this is rudimentary and fully expects that Figma's value is correct. Please see xxxxxx.

I am indeed seeing the same behavior, for both Helvetica Neue and Inter. See below, for Inter, as I'm outputting the Figma frame data for font weights.

```

Writing Figma base file...

Writing design tokens...
---> {
  fontFamily: 'Inter',
  fontPostScriptName: 'Inter-Bold',
  fontWeight: 700,
  paragraphSpacing: 1,
  textAutoResize: 'WIDTH_AND_HEIGHT',
  fontSize: 16,
  textAlignHorizontal: 'LEFT',
  textAlignVertical: 'CENTER',
  letterSpacing: 0,
  lineHeightPx: 18.75,
  lineHeightPercent: 100,
  lineHeightUnit: 'INTRINSIC_%'
}

Figmagic completed operations successfully!

~/Web/figmagic   main ±  npm run figmagic

> figmagic@4.4.0 figmagic
> node build/index.js


Attempting to fetch data from Figma API...

Writing Figma base file...

Writing design tokens...
---> {
  fontFamily: 'Inter',
  fontPostScriptName: 'Inter-SemiBold',
  fontWeight: 400,
  paragraphSpacing: 1,
  textAutoResize: 'WIDTH_AND_HEIGHT',
  fontSize: 16,
  textAlignHorizontal: 'LEFT',
  textAlignVertical: 'CENTER',
  letterSpacing: 0,
  lineHeightPx: 18.75,
  lineHeightPercent: 100,
  lineHeightUnit: 'INTRINSIC_%'
}

Figmagic completed operations successfully!

~/Web/figmagic   main ±  npm run figmagic

> figmagic@4.4.0 figmagic
> node build/index.js


Attempting to fetch data from Figma API...

Writing Figma base file...

Writing design tokens...
---> {
  fontFamily: 'Inter',
  fontPostScriptName: 'Inter-ExtraLight',
  fontWeight: 400,
  paragraphSpacing: 1,
  textAutoResize: 'WIDTH_AND_HEIGHT',
  fontSize: 16,
  textAlignHorizontal: 'LEFT',
  textAlignVertical: 'CENTER',
  letterSpacing: 0,
  lineHeightPx: 18.75,
  lineHeightPercent: 100,
  lineHeightUnit: 'INTRINSIC_%'
}

Figmagic completed operations successfully!

 mikael.vesavuori@PSC02FX1LRMD6R  ~/Web/figmagic   main ±  npm run figmagic

> figmagic@4.4.0 figmagic
> node build/index.js


Attempting to fetch data from Figma API...

Writing Figma base file...

Writing design tokens...
---> {
  fontFamily: 'Inter',
  fontPostScriptName: 'Inter-Thin',
  fontWeight: 100,
  paragraphSpacing: 1,
  textAutoResize: 'WIDTH_AND_HEIGHT',
  fontSize: 16,
  textAlignHorizontal: 'LEFT',
  textAlignVertical: 'CENTER',
  letterSpacing: 0,
  lineHeightPx: 18.75,
  lineHeightPercent: 100,
  lineHeightUnit: 'INTRINSIC_%'
}

Figmagic completed operations successfully!

 mikael.vesavuori@PSC02FX1LRMD6R  ~/Web/figmagic   main ±  
```

This seems to be an error on Figma's side, and I think the right course of action is to raise an issue in their support.

**Comment by mikaelvesavuori** [comment]
This seems to be the same thing, if also the font name has spaces, but the font style does not. Tried with `Iowan Old Style`, font style `Titling`: Came back as 400.

**Comment by Julian-Rojo-Beezy** [comment]
Thanks for the information!

Yep, looks like the space in the family name doesn't trigger the problem: I checked with "Noto Sans" (space in family name, but not in weights) and the issue doesn't happen
![2021-11-11_17h54_27](https://user-images.githubusercontent.com/70134058/141337668-95758e9e-36b1-473e-8896-bfa9670ac32c.png)

**Comment by mikaelvesavuori** [comment]
Is it OK to close this for now since it is not directly related to Figmagic
