### ISSUE TITLE
Invalid JavaScript when using tokens for CSS with camelizeTokenNames set to false

### ISSUE THREAD

**Issue by glouhaichi** [mikaelvesavuori/figmagic#153]
When setting the `camelizeTokenNames` option to false, the tokens are imported correctly without transformation. However, their use inside the elements' JS files presents invalid JavaScript, because it is using dot notation instead of bracket notation to call the tokens that have dashes in them.

**Current import (dot notation)**
```
const IxcCogniraButtonPrimaryLargeIconHoverCss = `
color: ${colors.ixc-cognira-color-primary-100};
font-size: ${fontSizes.ixc-cognira-headline-08};
`;
```

**Correct import (bracket notation)**
```
const IxcCogniraButtonPrimaryLargeIconHoverCss = `
color: ${colors["ixc-cognira-color-primary-100"]};
font-size: ${fontSizes["ixc-cognira-headline-08"]};
`;
```

**Comment by mikaelvesavuori** [comment]
This is now the default in version `4.4.1`.
