### ISSUE TITLE
Unable to run figmagic to generate raw Figma JSON data - error: msising "figmaToken" and "figmaUrl"

### ISSUE THREAD

**Issue by tomevans00** [mikaelvesavuori/figmagic#159]
Hello,

Me and my team work for a big enterprise and would love to use Figmagic in our design system. However, we're unable to successfully run `figmagic`

**Describe the bug**
Figmagic does not recognize token and url no matter how it is passed. Always giving this error when running `figmagic` to generate JSON dump: `Error: Missing one or more of required arguments: "figmaToken", "figmaUrl" when attempting to get data from Figma API!`

**To Reproduce**
Steps to reproduce the behavior, as per the documentation: https://github.com/mikaelvesavuori/figmagic#using-figmagic

1. create empty directory, navigate to inside new directory from command line
2. run `figmagic init` from command line to create `figmagic.json` file
3. create `.env` file in directory, add FIGMA_URL and FIGMA_TOKEN vars
5. run `npx figmagic`
6. receive error `Error: Missing one or more of required arguments: "figmaToken", "figmaUrl" when attempting to get data from Figma API!`
7. repeat with adding token and url to command line, same result
8. repeat with adding token and url to `figmagic.json`, same result

**Expected behavior**
Expected to generate a folder of the raw Figma JSON dump

**Desktop (please complete the following information):**
 - OS: macOS Catalina v10.15.7
 
**Additional context**
- When running with `--debug` you can see the token and url are indeed set in the user configuration

**Comment by mikaelvesavuori** [comment]
Hey!

Sounds weird. This is most likely some formatting or encoding issue. I just tested successfully using the below:

```
# Check Node version; should be recent (starting with 15-16 should work)
node -v

# Create directory, install, create .env file
mkdir figmagic-demo
cd figmagic-demo/
npm install figmagic -D
npx figmagic init 
touch .env

# Add values; URL used is for the template
echo "FIGMA_TOKEN=your-token-here" >> .env
echo "FIGMA_URL=K39TRbltDVcWFlpzw9r7Zh" >> .env

# Run
npx figmagic
```

**Comment by mikaelvesavuori** [comment]
Quick update. As expected, `.env` files will be very strict in their formatting. For example, this will break:

```bash
FIGMA_TOKEN="your-token-here"
FIGMA_URL="K39TRbltDVcWFlpzw9r7Zh"
```

Same with:

```bash
FIGMA_TOKEN = "your-token-here"
FIGMA_URL = K39TRbltDVcWFlpzw9r7Zh
```

**Comment by mikaelvesavuori** [comment]
Quick update. As expected, `.env` files will be very strict in their formatting. For example, this will break:

```bash
FIGMA_TOKEN="your-token-here"
FIGMA_URL="K39TRbltDVcWFlpzw9r7Zh"
```

Same with:

```bash
FIGMA_TOKEN = "your-token-here"
FIGMA_URL = K39TRbltDVcWFlpzw9r7Zh
```

**Comment by tomevans00** [comment]
Hey Mikael, following these instructions seemed to do the trick! I guess it was some formatting issue on my end. Thank you for your help!
