### ISSUE TITLE
Offline support

### ISSUE THREAD

**Issue by ppsirius** [mikaelvesavuori/figmagic#160]
Is it possible to transform the json file without giving Figma API?

**Comment by mikaelvesavuori** [comment]
If you have valid JSON you can set the ’recompileLocal’ option to not fetch new data via the Figma API. This should solve your issue. See https://github.com/mikaelvesavuori/figmagic#recompile-data-from-local-figma-json-file

**Comment by ppsirius** [comment]
Thanks, it's running but I get:
```Error: TypeError: Cannot read property 'children' of undefined```

**Comment by mikaelvesavuori** [comment]
I would expect that there is something that does not comply with the regular output and expectations on pages and overall format. Do you get it to work using the Figma API and following the instructions/prereqs?

**Comment by ppsirius** [comment]
I missed that I need to use your Figma template 🙈

**Comment by mikaelvesavuori** [comment]
Technically you do not need to use the template but you do need to follow the documented conventions :) Good you are going though! ;)
