### ISSUE TITLE
Elements generation issue

### ISSUE THREAD

**Issue by RmnMatusevich** [mikaelvesavuori/figmagic#178]
When you generate elements from figma file give an error in each generated element (.tsx component).

**To Reproduce**
1. Clone repository https://github.com/mikaelvesavuori/figmagic-example
2. Install dependencies
3. Add project to your figma https://www.figma.com/community/file/821094451476848226
4. Create .env with figma creds
5. npx figmagic
6. npx figmagic --syncElements, 

**Expected behavior**
Expected to get and generate elements from figma without issues with props in generated components.

**Screenshots**
![image](https://user-images.githubusercontent.com/47831494/199005985-5a034bc4-0083-4160-894f-3c41d7a96781.png)
![image](https://user-images.githubusercontent.com/47831494/199006087-304ff8c8-53af-4730-8870-fb82bdf9f0ec.png)

**Comment by mikaelvesavuori** [comment]
Hi @RmnMatusevich!

I just released `4.5.7` that should fix this. See https://github.com/mikaelvesavuori/figmagic/releases/tag/v4.5.7
