### ISSUE TITLE
RGBA opacity is not working

### ISSUE THREAD

**Issue by rodolfodosanjos** [mikaelvesavuori/figmagic#18]
**Describe the bug**
We defined RGBA colors with opacity on figmagic, but the RGBA color on the generated json does not have opacity

**To Reproduce**
1. Create a RGBA color with opacity on figma
2. Export to js with figmagic
3. Checkout generated js

**Expected behavior**
Generate RGBA with opacity

**Screenshots**
![figmagic bug](https://user-images.githubusercontent.com/13502536/79617995-37c5e580-80df-11ea-9bd4-bf7a48979d47.PNG)
Result:
 "primaryAction-Active": "rgba(24, 144, 255, 1)",

**Desktop (please complete the following information):**
 - OS: Windows
 - NodeJS v12.14.1
 - figmagic version: "^2.1.13",

**Comment by mikaelvesavuori** [comment]
Hey @rodolfodosanjos!

This should now be fixed in `3.0.9`.

Closing this for now.
