### ISSUE TITLE
Attempting to fetch data from Figma API; Error occurred while using the Figma API: "Error: connect ECONNREFUSED ::1:443"

### ISSUE THREAD

**Issue by whoiskatrin** [mikaelvesavuori/figmagic#189]
**Describe the bug**
Attempting to fetch data from Figma API; Error occurred while using the Figma API: "Error: connect ECONNREFUSED ::1:443"

**To Reproduce**
Option 1: tried running ./node_modules/figmagic/build/index.js --token {working_token} --url https://www.figma.com/file/7Otf78XDWzbvwHZQL7CCQ7/Figmagic-%E2%80%94-Design-System-template-4.0-\(Community\)\?node-id\=2605-12\&t\=2FYBx3hvpE0IdN5f-0

Option 2: tried running npx figmagic --token {working_token} --url https://www.figma.com/file/7Otf78XDWzbvwHZQL7CCQ7/Figmagic-%E2%80%94-Design-System-template-4.0-\(Community\)\?node-id\=2605-12\&t\=2FYBx3hvpE0IdN5f-0

**Expected behavior**
Generation to start and API being accessed 

**Desktop (please complete the following information):**
 - OS: MacOS

**Additional context**

**Comment by mikaelvesavuori** [comment]
I can't reproduce this issue, either with the full URL as you have shown, or with the better short-hand format `npx figmagic --token TOKEN --url 7Otf78XDWzbvwHZQL7CCQ7`.

The error, `ECONNREFUSED`, _could_ be connected either to issues either with the URL, given the full and extreme length of it (i.e. opt for the short-hand, as per above), or to some other network-related issue on your end.

**Comment by whoiskatrin** [comment]
@mikaelvesavuori the url is the one that suggested in the README and docs, but you are right, the short-hand format worked well, thank you
