### ISSUE TITLE
Global installation of figmagic cannot find file or directory

### ISSUE THREAD

**Issue by peterp** [mikaelvesavuori/figmagic#19]
When I attempt to run the figmagic CLI that's install globally:

```terminal
figmagic
/usr/local/bin/figmagic: line 2: //#: No such file or directory
Error: Could not find file!
```

1. `npm install -g figmagic`
2. `figmagic`
3. See error

Perhaps I'm meant to pass in a configuration file?

**Comment by peterp** [comment]
I see that this is a duplicate of #3. Maybe you can help me understand why this is failing, and how you would consider fixing it so that I can provide a PR?

**Comment by mikaelvesavuori** [comment]
Hi @peterp!

Let's try two things:

1. Are you running Node 13 or over? Just in case, you could try running `node --experimental-modules ./node_modules/figmagic/index.mjs`. Obviously this assumes that you are doing this within a project or relative to a non-global install, but I'd be happy to know if that worked better.

_but it's probably more likely to be:_

2. You should have a config file laying around, yes. In whatever directory you are in, could you add a file called `.figmagicrc` with same basic contents such as:

```json
{
  "fontUnit": "rem",
  "outputFileName": "figma.json",
  "outputFolderBaseFile": ".figmagic",
  "outputFolderTokens": "tokens",
  "outputTokenFormat": "mjs",
  "outputFolderElements": "elements",
  "spacingUnit": "rem",
  "usePostscriptFontNames": true,
  "token": "[FIGMA_TOKEN],
  "url": "[FIGMA_DOCUMENT_ID]"
}
```

**Comment by mikaelvesavuori** [comment]
The fix to this, given that the above resolves your problem, is (I would say) a better error message and throwing an error when there is no URL and/or token.

**Comment by mikaelvesavuori** [comment]
@peterp : I think I have verified that this happens when you don't have a `.figmagicrc` file. Please ensure you have one. I'll see if I can output a message or something when it does not exist.

**Comment by mikaelvesavuori** [comment]
Pushed to `3.0.10`. It will let you skip having a `.figmagicrc` file.

**Comment by mikaelvesavuori** [comment]
@peterp : Can you verify if the new version works for you?

**Comment by peterp** [comment]
Hey there @mikaelvesavuori, sorry for the delay, I'll get back to you before the end of the day!

**Comment by peterp** [comment]
Also, thank you so much for fixing this so quickly.

**Comment by peterp** [comment]
Works awesome, thank you so much!
