### ISSUE TITLE
Export CSS variables

### ISSUE THREAD

**Issue by mikaelvesavuori** [mikaelvesavuori/figmagic#190]
### Discussed in https://github.com/mikaelvesavuori/figmagic/discussions/168

<div type='discussions-op-text'>

<sup>Originally posted by **brunosarlo** August 23, 2022</sup>
Hi!

I'm looking forward to have figmagic export css variables. I couldn't find an easy way to do this yet. 

It has already been proposed as feature: https://github.com/mikaelvesavuori/figmagic/projects/1#card-38295671

Any ideas?

Thanks!</div>

**Comment by tjmusser** [comment]
Not sure if it helps @mikaelvesavuori but our project uses [Style Dictionary](https://amzn.github.io/style-dictionary/#/) to output figmagic data to CSS variables, LESS, SCSS, and XAML for multiple teams/projects.

We take the json output and then run it through style dictionary.

**Comment by mikaelvesavuori** [comment]
Added basic support in [version 4.5.9](https://github.com/mikaelvesavuori/figmagic/releases/tag/v4.5.9).
