### ISSUE TITLE
Figmagic Covert Art Is Not Working on the documentation page

### ISSUE THREAD

**Issue by David-Lazaro-Fernandez** [mikaelvesavuori/figmagic#193]
**Describe the bug**
Hi team I was looking into the documentation page and found that the current cover art is not showing itself 🚫

**To Reproduce**
1. Go to https://docs.figmagic.com/
2. Click on nothing

**Expected behavior**
Currently, the image is just showing the Alt of it.
I'm expecting to see the cover art of the project at the top of the main page.

**Screenshots**
Current page 

![image](https://github.com/mikaelvesavuori/figmagic/assets/57787993/5164e3cc-cc84-481a-ad43-ed9960ce8a0f)

Expected page look 

![image](https://github.com/mikaelvesavuori/figmagic/assets/57787993/713ef05d-829c-49d8-8517-12683233f01a)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: Version 118.0.5993.89 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
I solved the problem by just changing the cover art for the current one that is on the GitHub Readme.

**Comment by David-Lazaro-Fernandez** [comment]
Hi there, this happens also with the Example Project Image 
![image](https://github.com/mikaelvesavuori/figmagic/assets/57787993/32fd6ecb-a876-4901-be21-745df3c98a2a)

Expected Look 

![image](https://github.com/mikaelvesavuori/figmagic/assets/57787993/645e4aa9-cf2e-4402-b5f3-820d97b8fd88)

**Comment by mikaelvesavuori** [comment]
Hi! This is now fixed in https://github.com/mikaelvesavuori/figmagic/commit/432f040bfec7a8db4299e0fbd83d19edd0482e43
