### ISSUE TITLE
Could not retrieve any data. Are you missing a valid API key?

### ISSUE THREAD

**Issue by ranjith-n-7edge** [mikaelvesavuori/figmagic#199]
Figmagic is failing to retrieve data from Figma files, Once i run figmagic it is throwing error even if i provide right access to API Key.
I tried all different way to pass the FIGMA_URL and FIGMA_TOKEN in all different ways but no luck
![Screenshot from 2024-03-27 11-29-07](https://github.com/mikaelvesavuori/figmagic/assets/153505664/96f3c37d-886e-4501-b8b3-f80ca464836d)

 - Version: Node 20

**Comment by mikaelvesavuori** [comment]
Hi!

Something is going on on your side, and I don't have very much to go on to support you.

However, I've made you a small Bash script that will set up Figmagic in a working state, so that you can backtrack and learn from there:

```bash
#/bin/bash

mkdir figmagic-setup
cd figmagic-setup
npm install -S figmagic

# Change these demo values
echo 'FIGMA_TOKEN=123456-aeae1212-1d1d-1d1d-1d1d-abcdef123456
FIGMA_URL=K39TRbltDVcWFlpzw9r7Zh' >>.env

npx figmagic init

npx figmagic
```

**Comment by ranjith-n-7edge** [comment]
Hi @mikaelvesavuori Thank you for your support it works for me
I am using Ubuntu OS and if we install the figmagic globally by running `npm i figmagic -g` then i was getting the above error after using npx figmagic it works
Thank you for the quick response
