### ISSUE TITLE
Support for Multiple box-shadows

### ISSUE THREAD

**Issue by sareg0** [mikaelvesavuori/figmagic#23]
**Is your feature request related to a problem? Please describe.**
My team and I have been enjoying working with Figmagic, but we ran into a limitation; we work with compound box shadows and Figmagic "_currently only supports a single Drop Shadow_". Being able to export compound box-shadows would be a great feature for us.

**Describe the solution you'd like**
 I am wondering what might make it possible to export multiple shadows, and what limitations or gotchas there are to adding support for this.

**Describe alternatives you've considered**
The work-around we have used for right now is to add our shadows to our theme file manually (shown below), ignoring the file exported from Figmagic. 

**Additional context**
```js
shadows: {
  'overlay': '0px 0px 1px rgba(0, 0, 0, 0.04), 0px 1px 2px rgba(0, 0, 0, 0.04), 0px 2px 4px rgba(0, 0, 0, 0.04), 0px 4px 8px rgba(0, 0, 0, 0.04);',
  'pressed': '0px 1px 2px rgba(0, 0, 0, 0.03), 0px 2px 4px rgba(0, 0, 0, 0.03), 0px 4px 8px rgba(0, 0, 0, 0.03), 0px 8px 16px rgba(0, 0, 0, 0.03);',
  'raised': '0px 8px 32px rgba(0, 0, 0, 0.03), 0px 4px 16px rgba(0, 0, 0, 0.03), 0px 2px 8px rgba(0, 0, 0, 0.03), 0px 1px 4px rgba(0, 0, 0, 0.03);',
}
```

**Comment by mikaelvesavuori** [comment]
Hey @sareg0!

I will look into this. Looked at my notes (still not in the Projects board yet) and didn't find a TODO for this. Will come back to you and hopefully add it over the weekend.

**Comment by mikaelvesavuori** [comment]
Hi again. This was an easy fix. I've now added support for multiple Drop Shadows (other types will take a bit more time to implement). Support is added in 3.0.12.

**Comment by sareg0** [comment]
Woah! Thank you so much for the rapid response! It works like a ✨charm✨
