### ISSUE TITLE
"No such file or directory" error when running figmagic command

### ISSUE THREAD

**Issue by vspedr** [mikaelvesavuori/figmagic#3]
Node version: v11.10.0
OS: RHEL 7.6

Steps to reproduce:

- Clone this repo, `cd` into it and run `yarn setup`
- In a new terminal, go to the desired project directory, create `.env` file with figma credentials and run `figmagic`

Output:
`/usr/bin/env: node --experimental-modules --no-warnings: No such file or directory`

It seems that passing node options in the shebang is causing this error, since deleting the --experimental-modules and --no-warnings part makes it run node successfully but then if fails at the first import statement of the script.

```
/path/to/figmagic/index.mjs:3
import { createFolder } from "./bin/functions/createFolder.mjs";
       ^

SyntaxError: Unexpected token {
    at new Script (vm.js:85:7)
    at createScript (vm.js:266:10)
    at Object.runInThisContext (vm.js:314:10)
    at Module._compile (internal/modules/cjs/loader.js:698:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
    at internal/main/run_main_module.js:21:11
```

**Comment by mikaelvesavuori** [comment]
I've updated Figmagic to 1.0.2 which hopefully resolves this issue. It seems the shebang in 1.0.1 was not cross-platform.

**Comment by vspedr** [comment]
Hi @mikaelvesavuori, thanks for the update.

I still couldn't get it to work, here's a few things I tried:
- running figmagic after a clean install of the new version: `/path/to/node/v11.10.0/bin/figmagic: line 2: //#: No such file or directory`
- edited the shebang into this:
```
#!/bin/sh
":" //#; exec /usr/bin/env node --experimental-modules "$0" "$@"
```

The script then ran just fine, until it failed with a seemlingly unrelated error:
```
Missing required parameters to correctly run writeFile()!
```

I think the safest and cleanest way to check if it works at least for Mac and Linux users is to set up TravisCI with one build for each OS, and I think I can help you with that. Would you accept a PR?

**Comment by mikaelvesavuori** [comment]
Yeah, no problem! Thanks for looking into it.

**Comment by mikaelvesavuori** [comment]
Closing this because the issue was fixed in the merge.

**Comment by joeleduardo** [comment]
Trying on Mac im still having the error :(

**Comment by mikaelvesavuori** [comment]
Please add more details on your setup.

- What version of Node do you have?
- Are you trying to use Figmagic version 2.0.0?
- Are you following the API credentials instructions as per "Running Figmagic" in the README?
- Are you attempting to use Figmagic as a dependency for another project, or on its own?
- Have you tried running Figmagic with `node --experimental-modules index.mjs`? (assumes that you are inside the `figmagic` folder)

**Comment by wfortin** [comment]
Experiencing the same issue:
Running through npm 
```
        "tokens": "./node_modules/figmagic/index.mjs"
```
With the default `.figmagicrc` config in the README.md + .env with FIGMA_URL + FIGMA_TOKEN set.

Node version: v12.14.1
Figmagic version: 2.1.1 installed locally in the project

Output:
./node_modules/figmagic/index.mjs: line 2: //#: No such file or directory

**Comment by wfortin** [comment]
it works when adding `node --experimental-modules index.mjs` in front of the script, so my script now looks like so:

```
"tokens": "node --experimental-modules ./node_modules/figmagic/index.mjs"
```

**Comment by mikaelvesavuori** [comment]
Hey @wfortin. That message is not actually an error, per se. I'll spend some time to maybe remove that if possible and absolutely to create a "Job complete" message or some such thing. Unbelievably, there actually is no message to indicate all went well. Check your /tokens folder if you got your tokens.

If you DID get
```
Missing required parameters to correctly run writeFile()!
```
or anything like that, that **would** be an error, however.

**Comment by mikaelvesavuori** [comment]
The success message is now added in version 2.1.2.

**Comment by mikaelvesavuori** [comment]
Closing as this is no issue and its taken care of with a better message in 2.1.2 and the README which will be updated shortly.

**Comment by edisonmatoso** [comment]
same error ocurring with me.

OS: Win 10
Node: 12.16.1
figmagic: 2.1.13

**Comment by mikaelvesavuori** [comment]
@edisonmatoso : Could you see if my proposed resolution at [https://github.com/mikaelvesavuori/figmagic/issues/19](https://github.com/mikaelvesavuori/figmagic/issues/19) fixes this for you?

**Comment by edisonmatoso** [comment]
@mikaelvesavuori correct setup of `.figmagicrc` has fixed the error. my suggestion is create an error message more user-friendly when cause is incorrect setup of `.figmagicrc`

**Comment by mikaelvesavuori** [comment]
Thanks! Will add a ticket to look at potential improvement further on. Closing.
