### ISSUE TITLE
Add descriptive elements to the artboards by using "ignore" prefix

### ISSUE THREAD

**Issue by Stanko** [mikaelvesavuori/figmagic#30]
**Is your feature request related to a problem? Please describe.**

Currently artboards can only contain token elements and nothing else. It makes hard to onboard people and makes it easy to make mistakes and mess up the document.

**Describe the solution you'd like**

I think it would be very useful to be able to add elements that are ignored by figmagic's processing. Every element that has a certain prefix (e.g. `Ignore` or `ignore`) will be skipped by figmagic.

**Describe alternatives you've considered**

Currently we are adding notes outside of the artboards, but I think a way to ignore elements would create cleaner files. This also gives much more freedom to the design teams to organize their files.

**Additional context**
If you think this is a good feature, I'm willing to create a pull request.

Cheers!

**Comment by mikaelvesavuori** [comment]
Sounds like a good idea. It's added to the backlog now!

**Comment by Stanko** [comment]
Sweet, I'll open a PR this week.
