### ISSUE TITLE
Feature request: support for transforms as design tokens.

### ISSUE THREAD

**Issue by jchiem** [mikaelvesavuori/figmagic#37]
**Is your feature request related to a problem? Please describe.**
Would it be possible to add a way to support CSS [transform](https://developer.mozilla.org/en-US/docs/Web/CSS/transform) as design tokens? Such as `transform: scale()`, `transform: rotate()` etc.
From a code perspective it'd be useful to be able to use design tokens for setting these type of values.
 
Not sure if it's possible within Figma or not though...? 🤔

**Comment by mikaelvesavuori** [comment]
Hey @jchiem ,
Sounds like a potentially good idea!

I guess that info should be able to be derived from Figma. Will need to verify first.

**Comment by jchiem** [comment]
I discussed this a bit with team members in my project and we think it might make most sense to keep the design tokens to be referencing specifically the decimal/integer value for the design token value. So if you have `transform: scale(1.5)` the design token would probably be 1.5, but not sure if it would translate properly to how designers would work with it in Figma. 

Not sure exactly how it'd work for `transform: rotate` though since there it's also including `deg` if you use CSS.

**Comment by mikaelvesavuori** [comment]
I mean, just extracting string (fake floats) values like with Z indices is not too hard. It’s a bit your call: would something like a float number (i.e. ”1.5”) be something you would use?

**Comment by jchiem** [comment]
>would something like a float number (i.e. ”1.5”) be something you would use? 
I believe it would be yes.

> With degrees etc I suppose the actual value would never do any validation, just pass it on to whatever/wherever you use it
Yeah, I think that should work.

Sorry for the slow reply.
