### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by vspedr** [mikaelvesavuori/figmagic#5]
Hello again @mikaelvesavuori,

I really enjoyed using figmagic and I see there is a lot of potential for improvement to make it an even more useful tool. Here are some suggestions I'd like to see in the future, and if you agree, I can probably address some of these with PRs or we can discuss before making any decisions:
- [x] error handling: I see you added a few validation rules console.error messages in the newest version, but one problem that I ran into while working on #4 is that even when something goes wrong, e.g. invalid Figma token, the script still exits with status code 0. It would be better for a continuous integration environment if it actually threw an error and exited with a different status code;
- [x] unit tests: with CI set up, running automated unit tests is a breeze;
- [x] give the user an option of which module system to use for the output, e.g. ESM or CommonJS. In my use case webpack was not configured to load .mjs files so I used a script to rename the generated files as a workaround;

**Comment by mikaelvesavuori** [comment]
Added process.exit(1) to every error (well, except one bit which could do without, I believe), and also added "js" as a possible flag if you want .JS files.

**Comment by mikaelvesavuori** [comment]
Began writing some tests, using Jest. Let's see when those are done.

**Comment by mikaelvesavuori** [comment]
I've now integrated the work I've done on tests into both develop and master. They are in no way covering everything yet, but it's a whole lot better than nothing! :) Closing this for now, and please feel free to setup a dedicated new issue for anything to do with continuing CI or testing work.
