### ISSUE TITLE
Feature request: ignore tokens?

### ISSUE THREAD

**Issue by flo-sch** [mikaelvesavuori/figmagic#52]
Figmagic takes options to disable the graphics and elements sync:

```json
{
  "syncGraphics": false,
  "syncElements": false
}
```

Would it be possible to have a similar flag for tokens?

Context: I am using Figmagic (same Figma document) in 3 repositories:
- one UI package (fetching design tokens)
- 2 applications (syncing *only* graphics for now, importing tokens from the UI package)

I would just ensure tokens are not fetched unintentionally from within the "application" projects, since I want those to import the centralised tokens.

Does adding such a flag make sense?

I could also add `tokens` to `.gitignore` to make sure they would never be commited, but I think a flag could be more appropriate?

**Comment by flo-sch** [comment]
NOTE: I am looking at a way to package icons as well (which would remove the need for that feature), just haven't found a nice way yet to make that work

**Comment by mikaelvesavuori** [comment]
I will add this to the backlog and deal with in the on-going version 4.0 work. ETA for Figmagic 4.0 is in the coming 2-4 weeks.

**Comment by mikaelvesavuori** [comment]
This is implemented in version 4.
