### ISSUE TITLE
Feature request: Print hex colors as well as RGB values

### ISSUE THREAD

**Issue by tomsoderlund** [mikaelvesavuori/figmagic#54]
The CLI tool currently outputs:

    ! No matching token! Hard-coding to expected value: color: rgba(164, 164, 164, 1)

Desired:

    ! No matching token! Hard-coding to expected value: color: rgba(164, 164, 164, 1) (#A4A4A4, 100%)

This makes it easier to debug since colors are shown as (#A4A4A4, 100%) in Figma.

**Comment by mikaelvesavuori** [comment]
This should be possible to do. I will add it to the v4 backlog.

**Comment by mikaelvesavuori** [comment]
This should now be completed. Moving close to a v4 release. Now it's just mostly a matter of documentation work, plus your "font names diff" request.
