### ISSUE TITLE
Font names are different in Design Tokens and Elements’ CSS

### ISSUE THREAD

**Issue by tomsoderlund** [mikaelvesavuori/figmagic#55]
**Describe the bug**
Font names are different in Design Tokens and Elements’ CSS.

**To Reproduce**

1. Create a Figma design with "Inter" as font.
2. Export both Design Tokens and Elements.

**Expected behavior**

The same font names in both files.

**Screenshots**

![fontFamilies](https://user-images.githubusercontent.com/1368668/93448745-3a1dad00-f8d4-11ea-8e31-da8ea890e972.jpg)

![ButtonBigPrimaryCss](https://user-images.githubusercontent.com/1368668/93448760-3d189d80-f8d4-11ea-9ddc-585221a7a5a4.jpg)

**Comment by mikaelvesavuori** [comment]
Will add to v4 backlog!

**Comment by mikaelvesavuori** [comment]
I investigated this last weekend, and it's due to that both non-Postscript and Postscript font names are used under the hood.

Using non-Postscript names (like your "Inter" example) creates mayhem with font family matching (if adjusted out of the box with no other big changes), resulting in several font families overwriting each other, though all using the one family.

This is now mostly a logical exercise that I hope will not involve too many conditionals. Still in scope for v4, but may be taken out, depending on where my continued work goes.

**Comment by mikaelvesavuori** [comment]
This should now be fixed in version 4.

**Comment by tomsoderlund** [comment]
Can I test v4 somehow?

**Comment by mikaelvesavuori** [comment]
Yes. Depends a bit on how you run Figmagic today.

Given that you have it as a dependency in a project today, you should be able to explicitly specify the version in package.json as ”4.0.0-alpha”.

For global install, clone or download the repo. Ensure you have v4 branch active and then run ”npm install -g”. That should put the v4 alpha as the global binary for Figmagic.

**Comment by mikaelvesavuori** [comment]
I will add further notes after lunch.

**Comment by mikaelvesavuori** [comment]
And this is the current base configuration. You'll maybe notice that some flags are changing names, and that new ones are available.

```
export const baseConfig: Config = {
  debugMode: false,
  fontUnit: 'rem',
  letterSpacingUnit: 'em',
  opacitiesUnit: 'float',
  figmaData: 'figma.json',
  figmagicFolder: '.figmagic',
  outputFolderElements: 'elements',
  outputFolderGraphics: 'graphics',
  outputFolderTokens: 'tokens',
  outputFormatCss: 'ts',
  outputFormatDescription: 'md',
  outputFormatElements: 'tsx',
  outputFormatGraphics: 'svg',
  outputFormatStorybook: 'js',
  outputFormatTokens: 'ts',
  outputGraphicElements: false,
  outputGraphicElementsMap: false,
  outputScaleGraphics: 1,
  outputDataTypeToken: null,
  recompileLocal: false,
  remSize: 16,
  skipFileGeneration: {
    forceUpdate: true,
    skipCss: false,
    skipDescription: false,
    skipReact: false,
    skipStorybook: false,
    skipStyled: false
  },
  spacingUnit: 'rem',
  syncElements: false,
  syncGraphics: false,
  syncTokens: true,
  templates: {
    templatePathGraphic: 'templates/graphic',
    templatePathReact: 'templates/react',
    templatePathStorybook: 'templates/story',
    templatePathStyled: 'templates/styled'
  },
  token: '',
  url: '',
  usePostscriptFontNames: false
};
```
