### ISSUE TITLE
Support for forward slash (`/`) in Element naming (e.g. `MyButton / primary / :hover`)

### ISSUE THREAD

**Issue by tomsoderlund** [mikaelvesavuori/figmagic#56]
**Is your feature request related to a problem? Please describe.**
The forward slash (`/`) has a [special meaning in Figma components (also for names of color/text/effect styles)](https://www.figma.com/best-practices/components-styles-and-shared-libraries/organizing-and-creating-libraries/#forward-slash-naming). It allows you to create groups of similar components that can be easily swapped out.

<img width="253" alt="Swap_Instance" src="https://user-images.githubusercontent.com/1368668/94425893-fc027200-018c-11eb-9f2d-c75ab49eb516.png">

With multiple `/`, you can create nesting of components, e.g. `Button / primary / :hover`.

**Describe the solution you'd like**
- A component on _Elements_ page named `MyButton / primary / :hover` should be exported to CSS `MyButton.primary:hover { … }`.
- A component called `MyButton` should be exported to CSS `MyButton { … }`

_Nice-to-haves:_
- Support components with inheritance, e.g. if component `MyButton / :hover` is just an instance of `MyButton` with some color overrides, CSS values for `MyButton:hover` should still be exported.

**Describe alternatives you've considered**
Current structure e.g:

    ᠅ MyButton (component)
        ⬚ Normal (group)
            ▭ Normal (e.g. text, rectangle – NOT a group)
            ▭ Normal (e.g. text, rectangle – NOT a group)
            ▭ :hover (e.g. text, rectangle – NOT a group)

works but enforces a structure which is not optimal for Figma’s component system.

**Update:** I see now that Figmagic is parsing the slashes, but creates completely separate components for each group.

**Comment by mikaelvesavuori** [comment]
This may be problematic because of Unix/Mac and how the slash can be a folder separator. I'll probably have to add some amount of logic to handle that.

I will investigate when I have time!

**Comment by tomsoderlund** [comment]
@mikaelvesavuori I see now that Figmagic is indeed parsing the slashes, but creates completely separate components for each group, e.g. `Button\Normal`, `Button\Primary`.

**Comment by tomsoderlund** [comment]
From Figma’s documentation on how to use slash in layer naming:

<img width="730" alt="Figma_docs" src="https://user-images.githubusercontent.com/1368668/94439053-332e4e80-01a0-11eb-8094-39189b5824e2.png">

**Comment by mikaelvesavuori** [comment]
This will probably not be supported, since the Figmagic mental model is different enough from the Sketch/Figma "slash names" concept. Combined with the problems of Node and cross-platform parsing of slashes I don't see this as an immediate candidate for v4.

**Comment by mikaelvesavuori** [comment]
With a tiny bit of extra mental effort, I see that the main implication of changing this is that the entire behavior and structuring of (in Figmagic's case) classes will change. I will postpone this until at least after Figma Variants have been publicly available.
