### ISSUE TITLE
Opacities not output in colors.ts

### ISSUE THREAD

**Issue by ursooperduper** [mikaelvesavuori/figmagic#70]
**Bug Description**
When a color is output from Figma, the corresponding opacity is set to 1 regardless of the opacity set in Figma. 

**To Reproduce**
1. Create a rectangle in a Colors frame on the Design Tokens page in a Figma project. 
2. Set the color value to 0, 0, 0, 10%
3. Run figmagic and view the resulting colors.ts file

**Expected behavior**
The colors file should list that color as "blackFade10":rgba(0, 0, 0, .10)"

**Actual behavior**
The colors.ts file shows  "blackFade10": "rgba(0, 0, 0, 1)"

**Screenshots**
<img width="582" alt="Screen Shot 2020-10-15 at 4 21 57 PM" src="https://user-images.githubusercontent.com/1380417/96181885-aeaf3000-0f02-11eb-8f37-d28d46f57cd4.png">
<img width="397" alt="Screen Shot 2020-10-15 at 4 22 17 PM" src="https://user-images.githubusercontent.com/1380417/96181895-b2db4d80-0f02-11eb-86a3-e1adff8b27ea.png">

**Comment by mikaelvesavuori** [comment]
Hey! Thanks for reaching out. This should now be fixed in the ongoing `v4` branch.

**Comment by ursooperduper** [comment]
Awesome. I'll take a look at that branch.

**Comment by mikaelvesavuori** [comment]
`v4` is now public, and available in `4.0.0`. Closing.
