### ISSUE TITLE
Request for New Output Format: JSON

### ISSUE THREAD

**Issue by CodeByAlex** [mikaelvesavuori/figmagic#93]
**Is your feature request related to a problem? Please describe.**
I think it would be great if this tool could output the tokens as JSON so that they could be injected by other tools such as Style Dictionary by amazon. 

**Describe the solution you'd like**
During the token creation process, when js/ts is generated, json could also be an output option using the same naming.

**Describe alternatives you've considered**
converting the js to json on the consumer side

**Additional context**

**Comment by mikaelvesavuori** [comment]
Hi @CodeByAlex,

This feature was added to version `4.0.12` which just got released.

You either set `"outputFormatToken": "json"` in `.figmagicrc` or pass `--outputFormatTokens json` when you call Figmagic on the command line.

The result is going to be exactly what the regular TS/JS tokens look like, but without the warning on the first line, or the export statement.

Another option would be using `outputDataTypeTokens` and setting it to `enum` which is similar, but admittedly not identical. However, changes seem to have broken that functionality. I've put a private note on looking at that when I get time.
